/*
 * Copyright 2017 adaMada.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.jogjadamai.infest.credentials;

import java.awt.Color;

/**
 *
 * @author adaMada
 */
public class OperatorCredential extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorCredential
     */
    public OperatorCredential() {
        initComponents();
    }
    
    protected void verifyPassword(){
        String newPassword = "";
        for (char character : adminVerificationPasswordField.getPassword()) {
            newPassword = newPassword + character;
        }

        String verificationPassword = "";
        for (char character : adminNewPasswordField.getPassword()) {
            verificationPassword = verificationPassword + character;
        }

        if (newPassword.equals(verificationPassword)) {
            verifiedPasswordLabel.setText("Passwords match");
            verifiedPasswordLabel.setForeground(Color.GREEN);
        } else {
            verifiedPasswordLabel.setText("Passwords don't match");
            verifiedPasswordLabel.setForeground(Color.RED);
        }
//        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        operatorUsernameLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        adminNewPasswordField = new javax.swing.JPasswordField();
        operatorNewPasswordLabel = new javax.swing.JLabel();
        operatorConfirmPasswordLabel = new javax.swing.JLabel();
        adminVerificationPasswordField = new javax.swing.JPasswordField();
        operatorChangePasswordButton = new javax.swing.JButton();
        operatorCancelButton = new javax.swing.JButton();
        verifiedPasswordLabel = new javax.swing.JLabel();
        operatorUsernameField = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operator Credentials");
        setAlwaysOnTop(true);
        setName("operatorUsernameLabel"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        operatorUsernameLabel.setText("Username");
        operatorUsernameLabel.setName("operatorUsernameLabel"); // NOI18N

        adminNewPasswordField.setName("adminNewPasswordField"); // NOI18N
        adminNewPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newPasswordKeyReleased(evt);
            }
        });

        operatorNewPasswordLabel.setText("New Password");
        operatorNewPasswordLabel.setName("operatorNewPasswordLabel"); // NOI18N

        operatorConfirmPasswordLabel.setText("Confirm Password");
        operatorConfirmPasswordLabel.setName("operatorConfirmPasswordLabel"); // NOI18N

        adminVerificationPasswordField.setName("adminVerificationPasswordField"); // NOI18N
        adminVerificationPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adminVerificationKeyReleased(evt);
            }
        });

        operatorChangePasswordButton.setText("Change Password");
        operatorChangePasswordButton.setName("operatorChangePasswordButton"); // NOI18N
        operatorChangePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorChangePasswordButtonActionPerformed(evt);
            }
        });

        operatorCancelButton.setText("Cancel");
        operatorCancelButton.setName("operatorCancelButton"); // NOI18N
        operatorCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorCancelButtonActionPerformed(evt);
            }
        });

        verifiedPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verifiedPasswordLabel.setText(" ");

        operatorUsernameField.setName("operatorUsernameField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(operatorUsernameLabel)
                        .addGap(86, 86, 86)
                        .addComponent(operatorUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adminVerificationPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(operatorConfirmPasswordLabel)
                                    .addComponent(operatorCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(operatorNewPasswordLabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(adminNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(operatorChangePasswordButton))))
                            .addComponent(verifiedPasswordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operatorUsernameLabel)
                    .addComponent(operatorUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminNewPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatorNewPasswordLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(operatorConfirmPasswordLabel)
                    .addComponent(adminVerificationPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(verifiedPasswordLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operatorChangePasswordButton)
                    .addComponent(operatorCancelButton))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        adminNewPasswordField.getAccessibleContext().setAccessibleName("adminNewPasswordField");
        adminVerificationPasswordField.getAccessibleContext().setAccessibleName("adminVerificationPasswordField");
        operatorChangePasswordButton.getAccessibleContext().setAccessibleName("changePasswordAdminButton");
        operatorCancelButton.getAccessibleContext().setAccessibleName("cancelChangePasswordAdmin");
        verifiedPasswordLabel.getAccessibleContext().setAccessibleName("verifiedPasswordLabel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminVerificationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminVerificationKeyReleased
        verifyPassword();
    }//GEN-LAST:event_adminVerificationKeyReleased

    private void operatorChangePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorChangePasswordButtonActionPerformed
        
    }//GEN-LAST:event_operatorChangePasswordButtonActionPerformed

    private void operatorCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorCancelButtonActionPerformed
        
    }//GEN-LAST:event_operatorCancelButtonActionPerformed

    private void newPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPasswordKeyReleased
        if(adminVerificationPasswordField.getPassword().length == 0){
            verifiedPasswordLabel.setText(" ");
        }else {
            verifyPassword();
        }
        
    }//GEN-LAST:event_newPasswordKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperatorCredential.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperatorCredential.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperatorCredential.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperatorCredential.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperatorCredential().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPasswordField adminNewPasswordField;
    protected javax.swing.JPasswordField adminVerificationPasswordField;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    protected javax.swing.JButton operatorCancelButton;
    protected javax.swing.JButton operatorChangePasswordButton;
    private javax.swing.JLabel operatorConfirmPasswordLabel;
    private javax.swing.JLabel operatorNewPasswordLabel;
    protected javax.swing.JTextField operatorUsernameField;
    private javax.swing.JLabel operatorUsernameLabel;
    private javax.swing.JLabel verifiedPasswordLabel;
    // End of variables declaration//GEN-END:variables
}
